version: "3"

services:
  genshin-discord-bot:
    image: ghcr.io/lucifer7535/genshin-discord-bot:latest
    container_name: GenshinDiscordBot
    environment:
      - TZ=Asia/Taipei
      # ↓↓↓↓↓↓↓↓ Mandatory Settings ↓↓↓↓↓↓↓↓
      # Bot Application ID, obtained from Discord Developer webpage
      - APPLICATION_ID=123456789
      # Test server ID, used for testing slash commands; admin commands can only be used in this server
      - TEST_SERVER_ID=123456789
      # Bot Token, obtained from Discord Developer webpage
      - BOT_TOKEN=ABCD123456789
      # ==========================

      # ↓↓↓↓↓↓ Optional Settings ↓↓↓↓↓↓
      # Interval for Hoyolab daily check-in (in minutes)
      - SCHEDULE_DAILY_CHECKIN_INTERVAL=10
      # Interval for checking instant resin (in minutes)
      - SCHEDULE_CHECK_RESIN_INTERVAL=5
      # Waiting interval between each user during scheduled execution (in seconds)
      - SCHEDULE_LOOP_DELAY=2.0
      # Number of days until a user expires; users who haven't used any commands for this many days will be deleted
      - EXPIRED_USER_DAYS=180

      # Cooldown time for users to call slash commands repeatedly (in seconds)
      - SLASH_CMD_COOLDOWN=5.0
      # Timeout for long interactions in Discord (e.g., dropdown menus) (in seconds)
      - DISCORD_VIEW_LONG_TIMEOUT=1800
      # Timeout for short interactions in Discord (e.g., confirmation, selection buttons) (in seconds)
      - DISCORD_VIEW_SHORT_TIMEOUT=120
      # ==========================

      # ↓↓↓↓↓↓ Advanced Settings (Optional) ↓↓↓↓↓↓
      # Remote check-in API URL list
      # - DAILY_REWARD_API_LIST=["https://xxxx.xxx"]
      # Sentry DSN address setting
      # - SENTRY_SDK_DSN=https://xxxxx@xxxx.ingest.sentry.io/xxx
      # Prometheus server listening port
      # - PROMETHEUS_SERVER_PORT=9091
      # Address of hoyolab-geetest-webserver webpage service; if you want to share it with others, change it to your computer's public IP
      - GEETEST_SOLVER_URL=http://127.0.0.1:8081
      # ==========================
    volumes:
      - ./data:/app/data
      - ./cogs_external:/app/cogs_external
    restart: always

  # Service for configuring user graphical verification
  hoyolab-geetest-webserver:
    image: ghcr.io/lucifer7535/hoyolab-geetest-webserver:main
    container_name: HoyolabGeetestWebserver
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./data/bot/:/app/data/
    ports:
      # Left side 8081 should correspond to GEETEST_SOLVER_URL above
      - "8081:8000"
    restart: always

  # If you want to use Prometheus monitoring
  # 1. Uncomment PROMETHEUS_SERVER_PORT=9091 in the advanced settings above
  # 2. Modify the contents of data/prometheus.yml file
  #    - Set targets: ['genshin-discord-bot:9091']
  #    - Set remote_write
  # 3. Uncomment the entire section below
  # prometheus:
  #   image: prom/prometheus:v2.37.6
  #   container_name: Prometheus
  #   environment:
  #     - TZ=Asia/Taipei
  #   volumes:
  #     - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: always
