"""pure fiction

Revision ID: 1f8b10376483
Revises: fb6f7c8b91f2
Create Date: 2024-01-30 23:59:53.304596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8b10376483'
down_revision = 'fb6f7c8b91f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
